### ISSUE TITLE
Error when trying to commit

### ISSUE THREAD

**Issue by deser** [kentcdodds/validate-commit-msg#31]
Error: missing wizard prompter validate-commit-msg {
  "config": {}
}
    at lazyAssLogic (\node_modules\pre-git\node_modules\lazy-ass\index.js:93:14)
    at lazyAss (\node_modules\pre-git\node_modules\lazy-ass\index.js:98:28)
    at Object.pickWizard [as wizard] (\node_modules\pre-git\src\pre-git.js:317:3)
    at Object.<anonymous> (\node_modules\pre-git\bin\commit-msg.js:11:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

Settings are the next:
"config": {
    "pre-git": {
      "commit-msg": "validate-commit-msg",
      "pre-commit": [
        "npm run lint",
        "npm run testonly"
      ]
    }
  }

pre-git has 3.8.3  version

**Comment by kentcdodds** [comment]
My guess is this is a pre-git issue. @bahmutov?

**Comment by bahmutov** [comment]
Oh my! we need to move this issue to bahmutov/pre-git somehow

**Comment by kentcdodds** [comment]
@deser, please file this issue here: https://github.com/bahmutov/pre-git/issues/new

**Comment by deser** [comment]
done

**Comment by deser** [comment]
Thanks guys
